[
        "mail": "student1@example.com",
        "sisi_id": "21B1NUM0001",
        "firstname": "Оюутан1",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000001",
        "is_choosed": true,
        "proposed_number": 2
   ],
    [
        "mail": "student2@example.com",
        "sisi_id": "21B1NUM0002",
        "firstname": "Оюутан2",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000002",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student3@example.com",
        "sisi_id": "21B1NUM0003",
        "firstname": "Оюутан3",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000003",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student4@example.com",
        "sisi_id": "21B1NUM0004",
        "firstname": "Оюутан4",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000004",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student5@example.com",
        "sisi_id": "21B1NUM0005",
        "firstname": "Оюутан5",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000005",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student6@example.com",
        "sisi_id": "21B1NUM0006",
        "firstname": "Оюутан6",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000006",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student7@example.com",
        "sisi_id": "21B1NUM0007",
        "firstname": "Оюутан7",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000007",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student8@example.com",
        "sisi_id": "21B1NUM0008",
        "firstname": "Оюутан8",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000008",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student9@example.com",
        "sisi_id": "21B1NUM0009",
        "firstname": "Оюутан9",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000009",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student10@example.com",
        "sisi_id": "21B1NUM0010",
        "firstname": "Оюутан10",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000010",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student11@example.com",
        "sisi_id": "21B1NUM0011",
        "firstname": "Оюутан11",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000011",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student12@example.com",
        "sisi_id": "21B1NUM0012",
        "firstname": "Оюутан12",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000012",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student13@example.com",
        "sisi_id": "21B1NUM0013",
        "firstname": "Оюутан13",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000013",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student14@example.com",
        "sisi_id": "21B1NUM0014",
        "firstname": "Оюутан14",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000014",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student15@example.com",
        "sisi_id": "21B1NUM0015",
        "firstname": "Оюутан15",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000015",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student16@example.com",
        "sisi_id": "21B1NUM0016",
        "firstname": "Оюутан16",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000016",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student17@example.com",
        "sisi_id": "21B1NUM0017",
        "firstname": "Оюутан17",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000017",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student18@example.com",
        "sisi_id": "21B1NUM0018",
        "firstname": "Оюутан18",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000018",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student19@example.com",
        "sisi_id": "21B1NUM0019",
        "firstname": "Оюутан19",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000019",
        "is_choosed": true,
        "proposed_number": 2
  ],
    [
        "mail": "student20@example.com",
        "sisi_id": "21B1NUM0020",
        "firstname": "Оюутан20",
        "lastname": "Сурагч",
        "program": "Компьютерийн Ухаан",
        "dep_id": 1,
        "phone": "80000020",
        "is_choosed": true,
        "proposed_number": 2
  ]